# Generated by Django 5.2.12 on 2026-04-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('horario_entrada', models.DateTimeField()),
                ('horario_saida', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='pessoa',
            name='senha',
            field=models.CharField(default=12345, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
