# Generated by Django 6.0.4 on 2026-04-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbk', '0003_cadastrovisitanteportaria_registroacessoportaria'),
    ]

    operations = [
        # 0003 já cria a coluna `foto`; aqui só a tornamos opcional (evita duplicate column).
        migrations.AlterField(
            model_name='cadastrovisitanteportaria',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='portaria/visitantes/%Y/%m/'),
        ),
    ]
